### ISSUE TITLE
Exclude `svg use` targets from LRC - Rocket-scripts

### ISSUE THREAD

**Issue by Miraeld** [wp-media/rocket-scripts#34]
**Describe the bug**
Just need to exclude `svg use` targets from LRC within `rocket-scripts`

**Comment by jeawhanlee** [comment]
Don't we need to have a linked PR here?

**Comment by Miraeld** [comment]
@jeawhanlee Totally forgot to press the button "Create PR" this morning. 
I've just done it, sorry 🙏
